baseURL = "https://www.exegetic.biz/"
languageCode = "en-us"
title = "Exegetic"

googleAnalytics = "UA-40073522-2"

theme = "exegetic"

pygmentsCodeFences = true
# styles: https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "pygments"

[permalinks]
  blog = "/blog/:year/:month/:title/"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  subject = "subjects"
  tag = "tags"
  document = "documents"

[params]
  description = "The biggest challenge to initiating and maintaining a Data Science capability is finding the right people. That's where Exegetic comes into the picture. We recognise that there are many challenges to adopting and maintaining a small and nimble Data Science team. That's why we offer a flexible and economical solution: Data Science on Demand."
  favicon = "img/favicon.ico"
  [params.contact]
    title = "Contact"
    text = ""
  [params.about]
    [params.about.image]
      path = "img/exegetic-logo.svg"
      alt = "Exegetic Analytics"
  [params.what]
    [params.what.image]
      path = "img/exegetic-logo.svg"
      alt = "Exegetic Analytics"
  [params.how]
    [params.how.image]
      path = "img/exegetic-logo.svg"
      alt = "Exegetic Analytics"
  [params.clients]
    [params.clients.image]
      path = "https://via.placeholder.com/300"
      alt = "Watch"
